compile:
	javac -classpath ./LeapJava.jar MyListener.java InteractionBoxDemo.java

run:
	java -classpath "./LeapJava.jar:." InteractionBoxDemo

clean:
	rm *.class

all: 
	make compile; make run; make clean;
